services:
  - type: web
    name: hoopoe-ebikes
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MAIL_USERNAME
        value: hoopoebikes@gmail.com
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
